apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: npm
  template:
    metadata:
      name: npm
      labels:
        app: npm
    spec:
      containers:
      - image: sumitroopchandani/npm-demo:latest
        imagePullPolicy: Always
        name: app
        resources:
          requests:
            cpu: "10m"
            memory: "20Mi"
          limits:
            cpu: "50m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: npm
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: npm
